---
language: python
python:
  - 2.7
  - 3.6
cache: pip
sudo: required
services:
  - docker
matrix:
  fast_finish: true
env:
  matrix:
    - ANSIBLE=2.5
    - ANSIBLE=2.6
    - ANSIBLE=2.7
install:
  - pip install tox-travis
script:
  - tox
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
