---
- name: Lookup temporary MySQL root password
  shell: grep '{{ pxc_temp_password_regex }}' /var/log/mysqld.log | awk '{print $NF}'
  changed_when: false
  register: _pxc_temp_password

- name: Set the MySQL root password
  vars:
    _statement: "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ pxc_root_password }}'"
  command: mysql --connect-expired-password -p'{{ _pxc_temp_password.stdout }}' -e "{{ _statement }}"
  when: _pxc_temp_password.stdout != ""

- name: Copy .my.cnf file with root password credentials
  template:
    src: "root/.my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
  when: _pxc_temp_password.stdout != ""

- name: Remove temporary password line
  lineinfile:
    dest: /var/log/mysqld.log
    regexp: "{{ pxc_temp_password_regex }}"
    state: absent
  when: _pxc_temp_password.stdout != ""
