---
- name: Lookup temporary MySQL root password assigned when DB initialized first time
  shell: grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk '{print $NF}'
  changed_when: false
  register: _pxc_temp_password

- name: Set the MySQL root password
  shell: >
    mysql --connect-expired-password --password='{{ _pxc_temp_password.stdout }}' --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ pxc_root_password }}';"
  when: _pxc_temp_password.stdout != ""

- name: Delete temp password line from /var/log/mysqld.log file
  lineinfile:
    dest: /var/log/mysqld.log
    regexp: 'A temporary password is generated for root@localhost'
    state: absent
  when: _pxc_temp_password.stdout != ""
